-- USUARIO
CREATE TABLE USUARIO (
	IDUSUARIO 		BIGINT 			PRIMARY KEY,
	NOME 			VARCHAR(255) 	NOT NULL,
	ADMINISTRADOR	BOOLEAN			DEFAULT FALSE,
	LOGIN 			VARCHAR(255) 	NOT NULL,
	SENHA 			VARCHAR(255) 	NOT NULL

);

CREATE SEQUENCE IDUSUARIO;

--------------------------------------------

-- ITEMMENU

CREATE TABLE ITEMMENU (
	IDITEMMENU 	BIGINT 			PRIMARY KEY,
	DESCRICAO 	VARCHAR(255) 	NOT NULL,
	PATH 		VARCHAR(255) 	NOT NULL
);

--------------------------------------------

-- PERMISSAOUSUARIO

CREATE TABLE PERMISSAOUSUARIO (
	IDPERMISSAOUSUARIO 	BIGINT 			PRIMARY KEY,
	IDUSUARIO 			BIGINT 			NOT NULL,
	IDITEMMENU 			BIGINT 			NOT NULL,
	CONSTRAINT FKPERMISSAOUSUARIOUSUARIO FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO),
	CONSTRAINT FKPERMISSAOUSUARIOITEMMENU FOREIGN KEY (IDITEMMENU) REFERENCES ITEMMENU(IDITEMMENU)
);

CREATE SEQUENCE IDPERMISSAOUSUARIO;

--------------------------------------------

-- SEED

INSERT INTO USUARIO(IDUSUARIO, NOME, ADMINISTRADOR, LOGIN, SENHA) VALUES (NEXTVAL('IDUSUARIO'), 'ADMINISTRADOR', true, 'admin', 'admin');

